apiVersion: extensions/v1beta1 
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
  annotations:
    federation.kubernetes.io/deployment-preferences: |
      {
            "rebalance": true,
            "clusters": {
                "gce-us-east1": {
                    "minReplicas": 3,
                    "maxReplicas": 3,
                    "weight": 1
                },
                "gce-us-central1": {
                    "minReplicas": 0,
                    "maxReplicas": 0,
                    "weight": 1
                }
                "gce-us-west1": {
                    "minReplicas": 3,
                    "maxReplicas": 3,
                    "weight": 1
                }
            }
      }
spec:
  replicas: 6
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.10
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
