apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: mongo
  annotations:
    federation.kubernetes.io/replica-set-preferences: |
         {
              "rebalance": true,
              "clusters": {
                  "gce-us-east1": {
                      "minReplicas": 1,
                      "maxReplicas": 1,
                      "weight": 3
                  },
                  "gce-us-central1": {
                     "minReplicas": 1,
                     "maxReplicas": 2,
                     "weight": 2
                  }
                  "gce-us-west1": {
                     "minReplicas": 1,
                     "maxReplicas": 3,
                     "weight": 1
                  }
              }
          }
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - image: mongo
        name: mongo
        ports:
        - name: mongo
          containerPort: 27017
        args:
        - --replSet
        - rs0

