apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  labels:
    name: mongo
  name: mongo
spec:
  replicas: 4
  template:
    metadata:
      labels:
        name: mongo
    spec:
      containers:
      - image: mongo
        name: mongo
        ports:
        - name: mongo
          containerPort: 27017
          hostPort: 27017
        volumeMounts:
            - name: mongo-ephemeral-storage
              mountPath: /data/db
      volumes:
        - name: mongo-ephemeral-storage
          emptyDir: {}
