apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  labels:
    name: nginx 
  name: nginx
spec:
  template:
    metadata:
      labels:
        app: nginx
        name: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.10
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
