apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  labels:
    name: pacman
  name: pacman
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: pacman
    spec:
      containers:
      - image: gcr.io/ifontlabs/pacman-nginx-app:latest
        name: pacman
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http-server
